- test/distributed_exec.jl
Refs: https://github.com/JuliaLang/julia/pull/51979
> tests: do not check all fields of UndefVarError for egal

- src/managers.jl
Originally proposed in https://github.com/JuliaLang/julia/pull/50843
> Add warning about new workers not sharing a global state

- src/cluster.jl
- src/process_messages.jl
> do not call worker_from_id with pid<1

- test/distributed_exec.jl
- test/topology.jl
Fixes 
```
  | ┌ Warning: rmprocs: process 1 not removed
  | └ @ Distributed /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-master/julia-83f908a311/share/julia/stdlib/v1.12/Distributed/src/cluster.jl:1049
```
Fixes https://github.com/JuliaLang/Distributed.jl/issues/15
> Guard rmprocs in tests to avoid warning. Fix leaky stderr from SIGTERM test.

- src/clusterserialize.jl
As discussed in [1], the implicit creation of bindings through the setglobal! intrinsic was accidentally added in 1.9 unintentionally and will be removed (ideally) or at the very least deprecated in 1.11.
The recommended replacement syntax is `Core.eval(mod, Expr(:global, sym))` to introduce the binding and `invokelatest(setglobal!, mod, sym, val)` to set it. The invokelatest is not presently required, but may be required for https://github.com/JuliaLang/julia/pull/54654, so it's included in the recommendation.
[1] https://github.com/JuliaLang/julia/issues/54607
> Don't rely on implicit binding creation by setglobal

- src/managers.jl
- test/distributed_exec.jl
This allows for easier collection of core dumps.
X-ref: https://github.com/JuliaLang/julia/pull/45864
> Use `SIGQUIT` instead of `SIGTERM`

- README.md
The cross-page link is broken. Rather than fix it, I removed it because the API section is typically already on-screen when folks see this link.
The note syntax is not supported on github so I switched it to standard markdown.
> Fix markdown errors in README.md

- src/Distributed.jl
- test/distributed_exec.jl
> Fix RemoteChannel iterator interface

- src/managers.jl
Should close https://github.com/JuliaLang/julia/issues/45172
The `exeflags` kwarg is very confusing and can lead to unexpected behavior when passing multiple flags in a single string, a first step is to get better docs on it.
> Adding better docs to exeflags kwarg

- src/macros.jl
The random extra spaces screw up formatting: https://docs.julialang.org/en/v1.10.5/stdlib/Distributed/#Distributed.@everywhere
> Fix docstring of `@everywhere`

- .github/workflows/ci.yml
The advantage is that the whole depot will be cached instead of just the artifacts. Also deleted the build step since Distributed doesn't have a build.jl file.
> Use julia-actions/cache in CI

- README.md
All content is the same, except for the new section about how to use development versions on Julia 1.11+.
Fixes #113.
> Reformat README and update development instructions

- src/cluster.jl
According to a stacktrace from a hung DistributedNext CI job this task was causing the process to hang before exiting:
```julia
InterruptException()
_jl_mutex_unlock at C:/workdir/src\threading.c:1012
jl_mutex_unlock at C:/workdir/src\julia_locks.h:80 [inlined]
ijl_task_get_next at C:/workdir/src\scheduler.c:458
poptask at .\task.jl:1163
wait at .\task.jl:1172
task_done_hook at .\task.jl:839
jfptr_task_done_hook_98752.1 at C:\hostedtoolcache\windows\julia\nightly\x64\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2233 [inlined]
jl_finish_task at C:/workdir/src\task.c:338
start_task at C:/workdir/src\task.c:1274
From worker 82:	fatal: error thrown and no exception handler available.Unhandled Task ERROR: InterruptException:
Stacktrace:
[1] …
```
> Replace a timeout task with timedwait()

- test/distributed_exec.jl
Quick explanation of what the `GC tests for RemoteChannels` test does:
1. Create `RemoteChannel`s `rr` and `fstore` on worker 1 and worker 2 respectively from the master process. At this point only the master process knows about `rr` and `fstore`.
2. Master process calls `put!(fstore, rr)`, i.e. we remotecall worker 2 and put `rr` (which is owned worker 1 but is currently only known about by the master) into `fstore`.
3. Remotecall into worker 1 and check that it knows about `rr`.
Step 3 should succeed despite us never previously explicitly communicating with worker 1, because `serialize(::ClusterSerializer, ::RemoteChannel)` will send a message to the owner of the `RemoteChannel` to inform them of its existence (see `send_add_client()`). This happens asynchronously in step 2, and on rare …
> Fix a race condition in the tests

- docs/src/index.md
- src/Distributed.jl
`@everywhere` has (slightly surprising) behaviour for `using`/`import` statements that can best be avoided by using `remotecall_eval` directly, so i think `remotecall_eval` should be exported (or at least marked `public` but i think `export` is fine here.
Context:
The behaviour of `@everywhere` is that it tries to find `using`/`import` statements and run them on the calling process first, which means an `@everywhere` can't be defined inside a function if it contains a `using`/`import` (unless you add a hack to cause `@everywhere` to not find your `using`/`import`).
i.e. while this works
```julia
julia> module Foo end
Main.Foo
julia> @everywhere workers() begin
using .Foo
end
```
This fails:
```julia
julia> function f()
@everywhere workers() begin
using .Foo
end
end
ERROR: syntax: …
```
> Export `remotecall_eval`

- .github/workflows/ci.yml
- src/cluster.jl
- src/macros.jl
- src/managers.jl
- src/messages.jl
- src/process_messages.jl
- src/remotecall.jl
- test/distributed_exec.jl
- test/runtests.jl
- test/threads.jl
Co-authored by @IanButterworth 
- 2c5eee0 upstreams a fix for hangs from DistributedNext
- 0928d68 includes some threadsafety changes from reviewing #101 on DistributedNext
- f7ba3ca enables multiple threads in CI to shake out problems
- [multiple commits] reverts `@spawn` to `@async` to get tests passing. Moving back to `@spawn` will take more work, but it should be low priority because the main thread, where Distributed usually runs, will already be `sticky` anyway, so the gain is minor.
- [`fbf8c12` (#122)](https://github.com/JuliaLang/Distributed.jl/pull/122/commits/fbf8c12bc44a92ba001a4898ad4ec48544cb9f00) is necessary to avoid each worker in those tests re-precompiling any stdlibs they use. Speeds up macos runs by ~1 minute
- [`97fc237` …
> Thread-safety improvements. Add tests with multiple threads. CI improvements.

- src/clusterserialize.jl
The internal function `jl_set_const` is allowed during bootstrap only and ignores world age partition. This would give incorrect results after JuliaLang/julia#57150. Just eval the constant definition directly, which has well defined semantics.
> Don't use internal jl_set_const to create constants

- src/workerpool.jl
- test/distributed_exec.jl
Otherwise the worker would prematurely be put back into the pool, causing oversubscription. Also added a warning about oversubscription to the docstring for `remote_do(f, ::AbstractWorkerPool)`.
Fixes #81. Cherry-picked from https://github.com/JuliaParallel/DistributedNext.jl/pull/20.
> Specialize remotecall_pool(remotecall) to wait for the remotecall

- Project.toml
- src/workerpool.jl
- test/aqua.jl
- test/distributed_exec.jl
- test/runtests.jl
Fixes failure on julia CI https://github.com/JuliaLang/julia/pull/57162 
also adds the same ambiguity test here.
```
  | 2025-01-26 11:12:11 EST | ambiguous                                        (3) \|         failed at 2025-01-26T08:12:11.695
  | 2025-01-26 11:12:11 EST | Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-master/julia-94bacb2dc4/share/julia/test/ambiguous.jl:205
  | 2025-01-26 11:12:11 EST | Expression: isempty(detect_ambiguities(modules...; recursive = true, allowed_undefineds))
  | 2025-01-26 11:12:11 EST | Evaluated: isempty(Tuple{Method, Method}[(remotecall_pool(rc_f::typeof(remotecall), f, pool::AbstractWorkerPool, args...; kwargs...) …
```
> Fix ambiguity in remotecall_pool specialized for remotecall. Add test. Add Aqua tests.

- src/macros.jl
Instead we point users to `WorkerPool`, which will do load-balancing.
Fixes #76, cherry-picked from https://github.com/JuliaParallel/DistributedNext.jl/pull/22.
> Document that `@spawnat :any` doesn't do load-balancing
